name: Build and push
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build binary
      run: make bin
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/${{ secrets.PROJECT_ID_NUM }}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'
