name: Build and push
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
    - name: Build container
      run: make build
    - name: Tag container
      run: docker tag karmabot:latest ghcr.io/jdholdren/karmabot:${{ github.sha }}
    - name: Push container
      run: docker push ghcr.io/jdholdren/karmabot:${{ github.sha }}
