name: Build and push
on:
  push:
    tags:
      - v*
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    # Make sure that we don't build releases that don't pass checks
    - name: Run Tests
      run: make test
    - name: Linter Check
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45
        args: --tests=f
        skip-go-installation: true
        skip-pkg-cache: true
    # Building the binary and drafting a release
    - name: Build binary
      env:
      - CGO_ENABLED=1
      run: go build -o /karmabot .
    - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          files: |
            LICENSE
            karmabot
