name: Build and push
on:
  push:
    tags:
      - v*
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Build binary
      run: CGO_ENABLED=0 go build -o karmabot .
    - name: Build arm binary
      run: GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=0 go build -o karmabot_armv7 .
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LICENSE
          karmabot
          karmabot_armv7
        draft: true
