name: Build and push
on:
  push:
    tags:
      - v*
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build binary
      run: CGO_ENABLED=0 go build -o karmabot .

    - name: Build container
      run: make build
    - name: Tag container
      run: docker tag karmabot:latest ghcr.io/jdholdren/karmabot:${{ github.ref_name }}
    - name: Push container
      run: docker push ghcr.io/jdholdren/karmabot:${{ github.ref_name }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LICENSE
          karmabot
          karmabot_armv7
        draft: true
