name: Code Checks
on:
  push:
jobs:
  test_lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - name: Run Tests
      run: make test
    - name: Linter Check
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45
        args: --tests=f
        skip-go-installation: true
        skip-pkg-cache: true
